"""Provider-neutral canonical Studio contracts and persistence foundation."""

from .persistence import (
    CASConflict,
    DEFAULT_MIGRATIONS,
    FOUNDATION_SCHEMA_VERSION,
    Migration,
    NetworkInTransactionError,
    PersistenceError,
    SchemaCompatibilityError,
    SQLiteReadRepository,
    SQLiteWriteOwner,
    SQLiteWriteTransaction,
    WriteOwnerAlreadyRunning,
    WriteOwnerNotRunning,
    WriteQueueFull,
    assert_network_allowed,
    ensure_schema_compatibility,
)
from .primitives import (
    FindingSeverity,
    GateVerdict,
    LifecycleState,
    LogicalId,
    Provenance,
    SemanticRecordMetadata,
    SourceVersionBinding,
    VersionId,
    VersionRef,
)
from .versioning import (
    ContentHashMismatch,
    CurrentPointerNotFound,
    CurrentVersionPointer,
    StoredSemanticVersion,
    SupersessionRecord,
    VersionNotFound,
    VersionRepository,
    VersionRepositoryError,
)

__all__ = [
    "CASConflict",
    "ContentHashMismatch",
    "CurrentPointerNotFound",
    "CurrentVersionPointer",
    "DEFAULT_MIGRATIONS",
    "FOUNDATION_SCHEMA_VERSION",
    "FindingSeverity",
    "GateVerdict",
    "LifecycleState",
    "LogicalId",
    "Migration",
    "NetworkInTransactionError",
    "PersistenceError",
    "Provenance",
    "SchemaCompatibilityError",
    "SemanticRecordMetadata",
    "SourceVersionBinding",
    "SQLiteReadRepository",
    "SQLiteWriteOwner",
    "SQLiteWriteTransaction",
    "StoredSemanticVersion",
    "SupersessionRecord",
    "VersionId",
    "VersionNotFound",
    "VersionRef",
    "VersionRepository",
    "VersionRepositoryError",
    "WriteOwnerAlreadyRunning",
    "WriteOwnerNotRunning",
    "WriteQueueFull",
    "assert_network_allowed",
    "ensure_schema_compatibility",
]
